### ISSUE TITLE
Service Annotations

### ISSUE THREAD

**Issue by Hazerre** [thetredev/helm-charts#1]
Hey there. Your SteamCMD chart is great. My only request would be allow us to set annotations on the service through the use of the values yaml. This is very useful for things like MetalLB's IP address sharing. Thanks.

https://metallb.universe.tf/usage/#ip-address-sharing

**Comment by thetredev** [comment]
Thank you! I can try this weekend probably, I need to setup a new testing cluster anyway.

Just to make sure, you mean `metadata/annotations`, right? Like this:
```yaml
metadata:
  annotations:
    some-label-key: "some-label-value"
```

where you would define the whole `annotations` block yourself using `values.yaml`? For example
```yaml
deployment:
  containerName: counter-strike2
  pullPolicy: IfNotPresent
  game: cs2

network:
  # -----> ANNOTATIONS HERE <-----
  service:
    annotations:
      some-key: "some-value"
  ip: "192.168.178.20"
  ports:
    server: 27015
    rcon:
      enabled: true
    ssh:
      enabled: true
      port: 22
      secretName: ssh-access

storage: "5Gi"

environment:
  timezone: "Etc/UTC"
  map: de_dust2
  maxplayers: 32
```
